class RedisKey(object):
    storage_test_text = 'stt'
    username = 'un'
    cache_status = 'cs'
    creators = 'creators'
    catalog_entities = 'ce'
    role_entity = 're'
    whole_permission = 'wp'
    role_permission_post = '_permission'
    user_role_post = '_role'
